### ISSUE TITLE
Strip away `background-image:` and `background:`

### ISSUE THREAD

**Issue by yagudaev** [yagudaev/css-gradient-to-figma#17]
Copy gradients from webgradient.com results in input that looks like:

```
background-image: linear-gradient(to right, #43e97b 0%, #38f9d7 100%);
```

Pasting that in the plugin will show an error. Instead, we can simply ignore that part and let the user paste the gradient uninterrupted.

**Comment by Myrfion** [comment]
Hello, could you assign this one on me? Thanks

**Comment by yagudaev** [comment]
@Myrfion I would love that 😁. Also be aware of https://github.com/yagudaev/css-gradient-to-figma/pull/16. I'm hoping to have it reviewed and merged today

**Comment by yagudaev** [comment]
The code you are looking for is: https://github.com/yagudaev/css-gradient-to-figma/blob/main/src/shared/color.ts#L21, there is also a test file now.

You should be all clear to go now that #18 has been merged 😁

**Comment by Myrfion** [comment]
Hi, just wanted to approach it, so is it still an issue or it was resolved in #18 I am kinda confused 😅

**Comment by yagudaev** [comment]
@Myrfion #18 is resolved now, you have a green light 🟢. Go a head create a PR to solve this issue here.

Excited to see it 😁

**Comment by Myrfion** [comment]
I tried to put the value like `background-image: linear-gradient(to right, #43e97b 0%, #38f9d7 100%);
` and I don't see an error, seems to work fine 🤔

**Comment by yagudaev** [comment]
Oh very cool, looks like the value parser we used in #18 which is the same one used by PostCSS actually accounts for the property name too.

I'll close this one. Great find and @gluck thanks again for the sick PR.

@Myrfion there are two more good first issues if you want to try them here: https://github.com/yagudaev/css-gradient-to-figma/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22
